"""Added indexex for user_id and parent_id from table contents

Revision ID: d8399d2909a9
Revises: 4f190cef4945
Create Date: 2024-06-26 21:44:30.510979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8399d2909a9'
down_revision: Union[str, None] = '4f190cef4945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contents_parent_id'), 'contents', ['parent_id'], unique=False)
    op.create_index(op.f('ix_contents_user_id'), 'contents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_user_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_parent_id'), table_name='contents')
    # ### end Alembic commands ###
